
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public int Id { get; set; }

    public string name { get; set; }

    public Nullable<System.DateTime> startDate { get; set; }

    public Nullable<System.DateTime> endDate { get; set; }

    public Nullable<int> priority { get; set; }

    public Nullable<int> taskNo { get; set; }

    public string status { get; set; }

    public string manager { get; set; }

}

}
