

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementApp.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class ProjectManagementEntities : DbContext
{
    public ProjectManagementEntities()
        : base("name=ProjectManagementEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Manager> Managers { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<User> Users { get; set; }


    public virtual ObjectResult<SP_View_Task_Result> SP_View_Task(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_View_Task_Result>("SP_View_Task", searchParameter);
    }

}

}

